server {
  listen 80;
  add_header X-Content-Type-Options nosniff;
  add_header X-Frame-Options SAMEORIGIN;
  root /usr/share/nginx/html;
  index index.html;
  # health endpoint
  location = /healthz.txt { try_files $uri =404; add_header Cache-Control "no-store"; }
  # mkdocs is static; try file or dir
  location / { try_files $uri $uri/ /index.html; }
}
