server {
  listen 80;
  server_name _;
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  add_header X-Content-Type-Options nosniff;
  add_header X-Frame-Options SAMEORIGIN;

  root /usr/share/nginx/html;
  index index.html;

  location = /healthz.txt { try_files $uri =404; add_header Cache-Control "no-store"; }

  # MkDocs is static; allow files/dirs; SPA fallback safe for search/index
  location / { try_files $uri $uri/ /index.html; }
}
