deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    - name: Verify deploy dir exists
      run: |
        test -d deploy || { echo "Missing directory: deploy"; ls -la; exit 1; }
        test -f deploy/docker-compose.yml || { echo "Missing file: deploy/docker-compose.yml"; exit 1; }
        test -f deploy/Caddyfile || { echo "Missing file: deploy/Caddyfile"; exit 1; }

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Ensure remote dir and ownership
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} '
          sudo mkdir -p /opt/impious/deploy &&
          sudo chown -R $USER:users /opt/impious
        '

    - name: Upload deploy directory (tar over SSH)
      run: |
        tar -C deploy -cf - . | ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} \
          "tar -C /opt/impious/deploy -xf -"

    - name: Compose up on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} '
          set -e
          cd /opt/impious/deploy
          (docker compose pull || docker-compose pull)
          (docker compose up -d --remove-orphans || docker-compose up -d --remove-orphans)
        '
