name: build-and-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show workspace
        run: |
          set -e
          echo "Branch: $(git rev-parse --abbrev-ref HEAD)"
          echo "::group::ls-root"; ls -la; echo "::endgroup::"
          echo "::group::ls-lore"; find lore-site -maxdepth 2 -type f -print 2>/dev/null || true; echo "::endgroup::"
          echo "::group::ls-game"; find game-api -maxdepth 2 -type f -print 2>/dev/null || true; echo "::endgroup::"
          echo "::group::ls-deploy"; find deploy -maxdepth 2 -type f -print 2>/dev/null || true; echo "::endgroup::"
      - name: Verify required files exist
        run: |
          set -e
          test -f lore-site/Dockerfile               || { echo "Missing lore-site/Dockerfile"; exit 1; }
          test -f lore-site/site/index.html          || { echo "Missing lore-site/site/index.html"; exit 1; }
          test -f game-api/Dockerfile                || { echo "Missing game-api/Dockerfile"; exit 1; }
          test -f game-api/server.js                 || { echo "Missing game-api/server.js"; exit 1; }
          test -f deploy/docker-compose.yml          || { echo "Missing deploy/docker-compose.yml"; exit 1; }
          test -f deploy/Caddyfile                   || { echo "Missing deploy/Caddyfile"; exit 1; }
          echo "Preflight passed."

  build:
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate GHCR_PAT is present
        run: |
          test -n "${{ secrets.GHCR_PAT }}" || { echo "GHCR_PAT secret is missing or empty"; exit 1; }

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: intunewithnature
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & push lore-site (latest + SHA)
        run: |
          TAG=ghcr.io/${{ github.repository_owner }}/lore-site
          SHA=${{ github.sha }}
          docker build -t $TAG:latest -t $TAG:$SHA ./lore-site
          docker push $TAG:latest
          docker push $TAG:$SHA

      - name: Build & push werewolf-game (latest + SHA)
        run: |
          TAG=ghcr.io/${{ github.repository_owner }}/werewolf-game
          SHA=${{ github.sha }}
          docker build -t $TAG:latest -t $TAG:$SHA ./game-api
          docker push $TAG:latest
          docker push $TAG:$SHA

      - name: Build & push impious-wiki (latest + SHA)
        run: |
          TAG="ghcr.io/${{ github.repository_owner }}/impious-wiki"
          SHA="${{ github.sha }}"
          docker build -t "$TAG:latest" -t "$TAG:$SHA" ./wiki
          docker push "$TAG:latest"
          docker push "$TAG:$SHA"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Ensure remote dir
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} 'mkdir -p /opt/impious/deploy'

      - name: Copy deploy files
        run: scp -o StrictHostKeyChecking=no -r deploy/* ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/opt/impious/deploy/

      - name: Compose up on server (build wiki locally, pull others)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} '
            set -e
            cd /opt/impious/deploy
            (docker compose pull caddy lore game status || docker-compose pull caddy lore game status) || true
            (docker compose build wiki || docker-compose build wiki)
            (docker compose up -d --remove-orphans || docker-compose up -d --remove-orphans)
          '
