name: build-and-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify required files
        run: |
          test -f lore-site/Dockerfile
          test -f lore-site/site/index.html
          test -f game-api/Dockerfile
          test -f game-api/server.js
          test -f deploy/docker-compose.yml
          test -f deploy/Caddyfile

  build_lore:
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: intunewithnature
          password: ${{ secrets.GHCR_PAT }}
      - name: Build & push lore-site
        run: |
          SHORT=$(echo $GITHUB_SHA | cut -c1-7)
          IMAGE=ghcr.io/${{ github.repository_owner }}/lore-site
          BRANCH="${GITHUB_REF##*/}"
          if [ "$BRANCH" = "main" ]; then
            docker buildx build --push -t $IMAGE:latest -t $IMAGE:sha-$SHORT lore-site
          else
            docker buildx build --push -t $IMAGE:$BRANCH -t $IMAGE:sha-$SHORT lore-site
          fi

  build_game:
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: intunewithnature
          password: ${{ secrets.GHCR_PAT }}
      - name: Build & push werewolf-game
        run: |
          SHORT=$(echo $GITHUB_SHA | cut -c1-7)
          IMAGE=ghcr.io/${{ github.repository_owner }}/werewolf-game
          BRANCH="${GITHUB_REF##*/}"
          if [ "$BRANCH" = "main" ]; then
            docker buildx build --push -t $IMAGE:latest -t $IMAGE:sha-$SHORT game-api
          else
            docker buildx build --push -t $IMAGE:$BRANCH -t $IMAGE:sha-$SHORT game-api
          fi

  build_wiki:
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: intunewithnature
          password: ${{ secrets.GHCR_PAT }}
      - name: Build & push impious-wiki
        run: |
          SHORT=$(echo $GITHUB_SHA | cut -c1-7)
          IMAGE=ghcr.io/${{ github.repository_owner }}/impious-wiki
          BRANCH="${GITHUB_REF##*/}"
          if [ "$BRANCH" = "main" ]; then
            docker buildx build --push -t $IMAGE:latest -t $IMAGE:sha-$SHORT wiki
          else
            docker buildx build --push -t $IMAGE:$BRANCH -t $IMAGE:sha-$SHORT wiki
          fi

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [build_lore, build_game, build_wiki]
    runs-on: ubuntu-latest
    - name: Checkout repo
      uses: actions/checkout@v4
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Sync deploy files
        run: |
          scp -o StrictHostKeyChecking=no -r deploy/* ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/opt/impious/deploy/

      - name: Deploy via Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} <<'EOF'
            cd /opt/impious/deploy
            docker compose pull
            docker compose up -d --remove-orphans
            docker image prune -f
            docker compose ps
            echo "--- Health check impious.io ---"
            curl -fsSI https://impious.io || echo "impious.io failed"
            echo "--- Health check game ---"
            curl -fsSI https://game.impious.io/healthz || echo "game failed"
          EOF
